.PHONY: clean All

All:
	@echo "----------Building project:[ Section8_challenge - Debug ]----------"
	@cd "Section8_challenge" && "$(MAKE)" -f  "Section8_challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section8_challenge - Debug ]----------"
	@cd "Section8_challenge" && "$(MAKE)" -f  "Section8_challenge.mk" clean
