.PHONY: clean All

All:
	@echo "----------Building project:[ Section1_Challenge - Debug ]----------"
	@cd "Section1_Challenge" && "$(MAKE)" -f  "Section1_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section1_Challenge - Debug ]----------"
	@cd "Section1_Challenge" && "$(MAKE)" -f  "Section1_Challenge.mk" clean
