.PHONY: clean All

All:
	@echo "----------Building project:[ Section7_challenge - Debug ]----------"
	@cd "Section7_challenge" && "$(MAKE)" -f  "Section7_challenge.mk"
clean:
	@echo "----------Cleaning project:[ Section7_challenge - Debug ]----------"
	@cd "Section7_challenge" && "$(MAKE)" -f  "Section7_challenge.mk" clean
