.PHONY: clean All

All:
	@echo "----------Building project:[ LetterPyramidChallenge - Debug ]----------"
	@cd "LetterPyramidChallenge" && "$(MAKE)" -f  "LetterPyramidChallenge.mk"
clean:
	@echo "----------Cleaning project:[ LetterPyramidChallenge - Debug ]----------"
	@cd "LetterPyramidChallenge" && "$(MAKE)" -f  "LetterPyramidChallenge.mk" clean
