.PHONY: clean All

All:
	@echo "----------Building project:[ ReadFile_3 - Debug ]----------"
	@cd "ReadFile_3" && "$(MAKE)" -f  "ReadFile_3.mk"
clean:
	@echo "----------Cleaning project:[ ReadFile_3 - Debug ]----------"
	@cd "ReadFile_3" && "$(MAKE)" -f  "ReadFile_3.mk" clean
