.PHONY: clean All

All:
	@echo "----------Building project:[ OOP_Practice2 - Debug ]----------"
	@cd "OOP_Practice2" && "$(MAKE)" -f  "OOP_Practice2.mk"
clean:
	@echo "----------Cleaning project:[ OOP_Practice2 - Debug ]----------"
	@cd "OOP_Practice2" && "$(MAKE)" -f  "OOP_Practice2.mk" clean
