.PHONY: clean All

All:
	@echo "----------Building project:[ Constructors - Debug ]----------"
	@cd "Constructors" && "$(MAKE)" -f  "Constructors.mk"
clean:
	@echo "----------Cleaning project:[ Constructors - Debug ]----------"
	@cd "Constructors" && "$(MAKE)" -f  "Constructors.mk" clean
