.PHONY: clean All

All:
	@echo "----------Building project:[ OOP_Practice - Debug ]----------"
	@cd "OOP_Practice" && "$(MAKE)" -f  "OOP_Practice.mk"
clean:
	@echo "----------Cleaning project:[ OOP_Practice - Debug ]----------"
	@cd "OOP_Practice" && "$(MAKE)" -f  "OOP_Practice.mk" clean
