.PHONY: clean All

All:
	@echo "----------Building project:[ ImplementingMethods1 - Debug ]----------"
	@cd "ImplementingMethods" && "$(MAKE)" -f  "ImplementingMethods1.mk"
clean:
	@echo "----------Cleaning project:[ ImplementingMethods1 - Debug ]----------"
	@cd "ImplementingMethods" && "$(MAKE)" -f  "ImplementingMethods1.mk" clean
